"""empty message

Revision ID: 6c87b007d2b5
Revises: 
Create Date: 2021-11-08 20:35:42.200278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c87b007d2b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expense_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['budget_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('MonthlyTotals')
    op.drop_table('Transactions')
    op.add_column('goals', sa.Column('due_date', sa.Date(), nullable=False))
    op.add_column('goals', sa.Column('price_required', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'price_required')
    op.drop_column('goals', 'due_date')
    op.create_table('Transactions',
    sa.Column('Receipt No.', sa.TEXT(), nullable=True),
    sa.Column('Completion Time', sa.TEXT(), nullable=True),
    sa.Column('Details', sa.TEXT(), nullable=True),
    sa.Column('Transaction', sa.TEXT(), nullable=True),
    sa.Column('Paid In', sa.TEXT(), nullable=True),
    sa.Column('Withdrawn', sa.TEXT(), nullable=True),
    sa.Column('Balance', sa.TEXT(), nullable=True)
    )
    op.create_table('MonthlyTotals',
    sa.Column('Transaction Type', sa.TEXT(), nullable=True),
    sa.Column('Paid In', sa.TEXT(), nullable=True),
    sa.Column('Paid Out', sa.TEXT(), nullable=True),
    sa.Column('dateFrom', sa.TIMESTAMP(), nullable=True),
    sa.Column('dateTo', sa.TIMESTAMP(), nullable=True)
    )
    op.drop_table('budget')
    op.drop_table('budget_category')
    # ### end Alembic commands ###
