"""empty message

Revision ID: ae096bbf0941
Revises: 6c87b007d2b5
Create Date: 2021-11-08 21:58:17.166756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae096bbf0941'
down_revision = '6c87b007d2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('budget_category', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('goals', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'timestamp')
    op.drop_column('budget_category', 'timestamp')
    op.drop_column('budget', 'timestamp')
    # ### end Alembic commands ###
